-- >> zhd
if game.GameId == 10379775646 then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/84c44aab915b6c93dd508adda8fba8f2.lua"))()
    -- >> zhs
elseif game.GameId == 10347630129 then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/84c44aab915b6c93dd508adda8fba8f2.lua"))()
    -- >> des hood
elseif game.GameId == 10390419074 then
    loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/84c44aab915b6c93dd508adda8fba8f2.lua"))()
end
